# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Shashwat\Documents\PSoC Creator\Empty\Blink_with_button_interrupt.cydsn\Blink_with_button_interrupt.cyprj
# Date: Fri, 18 Jan 2019 04:22:22 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for C:\Users\Shashwat\Documents\PSoC Creator\Empty\Blink_with_button_interrupt.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Shashwat\Documents\PSoC Creator\Empty\Blink_with_button_interrupt.cydsn\Blink_with_button_interrupt.cyprj
# Date: Fri, 18 Jan 2019 04:22:17 GMT
